print("_" * 70)
print("\t\t\tBREAD BASKET")
print("\t\"Looking for a healthy breakfast, this is the place for you!!\"")
print("_" * 70)
print("Raisin Toast\t\t\t\t\t\t$2.50")
print("French Toast\t\t\t\t\t\t$2.80")
print("Mushroom Toast\t\t\t\t\t\t$3.00")
print("Pancake\t\t\t\t\t\t\t$4.00")
print("Pancake with Ice-cream\t\t\t\t\t$7.50")
print("Chef's speciality\t\t\t\t\t$10.00")
print("_" * 70)